### ISSUE TITLE
easy_docker测试用例

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/easy_test#1]
- [x] easy_sample_make的功能验证
- [x] easy_ai的功能验证
- [x] easy_perception的功能验证

**Comment by foww-0001** [comment]
easy_docker测试用例：
[测试用例](https://github.com/MiniBullLab/easy_test/blob/main/%E6%B5%8B%E8%AF%95%E6%96%87%E6%A1%A3/%E6%B5%8B%E8%AF%95%E7%94%A8%E4%BE%8B/easy_docker%E6%B5%8B%E8%AF%95.md)
easy_docker测试结果：
[测试结果](https://github.com/MiniBullLab/easy_test/blob/main/%E6%B5%8B%E8%AF%95%E6%96%87%E6%A1%A3/%E6%B5%8B%E8%AF%95%E6%80%BB%E7%BB%93/easy_docker%E6%B5%8B%E8%AF%95%E6%80%BB%E7%BB%93/2021-9-23easy-docker%E6%B5%8B%E8%AF%95%E6%80%BB%E7%BB%93.md)

**Comment by kingwangxiang** [comment]
测试已完成。
