### ISSUE TITLE
pytorch版本升级测试

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_test#3]
主要修改了torch和torchvision的环境，使用torch==1.6.0和torchvision==0.7.0，测试内容：
- [x] classnet
- [x] denet
- [x] segnet

**Comment by foww-0001** [comment]
测试结果文档：
[测试结果](https://github.com/MiniBullLab/easy_test/blob/main/%E6%B5%8B%E8%AF%95%E6%96%87%E6%A1%A3/%E6%B5%8B%E8%AF%95%E6%80%BB%E7%BB%93/easy_docker%E6%B5%8B%E8%AF%95%E6%80%BB%E7%BB%93/2021-10-12easy-docker%E6%B5%8B%E8%AF%95%E6%80%BB%E7%BB%93.md)

**Comment by foww-0001** [comment]
denet在下位机无法运行，具体错误是转换模型的时候的层名称对不上。
```
Warning: ignoring unknown user output(s): ['det_output0', 'det_output1', 'det_output2']
```

**Comment by foww-0001** [comment]
先使用layer来对输出层进行命名。

**Comment by lpj0822** [comment]
使用torch==1.6.0和torchvision==0.7.0

**Comment by MiniBullLab** [comment]
Warning: ignoring unknown user output(s): ['layer_0', 'layer_1', 'layer_2']

**Comment by MiniBullLab** [comment]
通过代码发现现在是通过name而不是top来进行命名。

**Comment by foww-0001** [comment]
使用安霸CNNGEN的onnx转换可以让Denet跑通过。

**Comment by foww-0001** [comment]
记录问题：目前的Amba的CNNGEN中的caffe转换后的层名不再使用top输出的名称，而是使用layer name的名称作为转换后bin的输出名称。
