### ISSUE TITLE
pytorch cpu版本升级

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_test#5]
主要修改了torch和torchvision的环境，使用torch==1.6.0和torchvision==0.7.0，测试内容（满足上位机运行）：
- [x] classnet
- [x] denet
- [x] segnet

**Comment by foww-0001** [comment]
运行下面脚步安装cpu版本pytorch：
```
pip3 install https://download.pytorch.org/whl/cpu/torch-1.6.0%2Bcpu-cp36-cp36m-linux_x86_64.whl
```

**Comment by MiniBullLab** [comment]
cpu inference测试

**Comment by foww-0001** [comment]
inference已测试完毕，可以试一下

**Comment by foww-0001** [comment]
具体cpu运行时间如下：
classnet: 30ms
detnet: 250ms
segnet: 1200ms

**Comment by kingwangxiang** [comment]
测试已经完成。
